# Version Config
api: 2
# Configuration
version:
  number: 552
  name: 5.5.2-Beta
  changelog: 19.10, ElementaryOS 5.1 & LinuxMint 19.3 Support
# Stats reporting
stats:
  report: false
  node: https://stats.ae.prasadt.com/report
