# Version Config
api: 2
# Configuraion
version:
  number: 537
  name: 5.3.7
  changelog: Support for ROS & Duo-Unix repo, Cosmic+Tessa
# Stats reporting
stats:
  report: false
  node: https://stats.ae.prasadt.com/report
